import type { OpsTask } from "@/types";

function tl(time: string, action: string) {
  return { time, action };
}

export const tasks: OpsTask[] = [
  { id: "OT-001", title: "Fix leaking faucet in Room 204", description: "The staff room sink faucet has been leaking steadily for two days.", staffInstructions: "1. Turn off the water supply valve under the sink.\n2. Replace the worn washer.\n3. Test for leaks before closing up the area.", priority: "high", status: "in_progress", category: "maintenance", assigneeId: "TM001", createdAt: "2026-07-10", dueDate: "2026-07-14", estimatedHours: 2, needsHelp: false, timeline: [tl("2026-07-10", "Task created and assigned to John Smith"), tl("2026-07-11", "Started working on task")] },
  { id: "OT-002", title: "Update visitor log system", description: "Digitize the paper visitor log at the main gate into the new tablet system.", staffInstructions: "1. Set up the tablet at the security desk.\n2. Migrate the last 30 days of paper entries.\n3. Train the gate guard on the new flow.", priority: "medium", status: "pending", category: "administrative", assigneeId: "TM002", createdAt: "2026-07-12", dueDate: "2026-07-20", estimatedHours: 3, needsHelp: false, timeline: [tl("2026-07-12", "Task created and assigned to Sarah Johnson")] },
  { id: "OT-003", title: "Restock cleaning supplies - Building B", description: "Building B's supply closet is nearly empty for the second floor.", staffInstructions: "1. Check current inventory against the standard stock list.\n2. Requisition missing items from the central store.\n3. Restock the closet shelves.", priority: "low", status: "completed", category: "facilities", assigneeId: "TM004", createdAt: "2026-07-08", dueDate: "2026-07-13", completedAt: "2026-07-13", approvalStatus: "pending", estimatedHours: 1, needsHelp: false, timeline: [tl("2026-07-08", "Task created and assigned to Lisa Chen"), tl("2026-07-13", "Marked as done, awaiting approval")] },
  { id: "OT-004", title: "Order new lab equipment", description: "Chemistry lab needs 6 replacement burettes and 2 digital scales.", staffInstructions: "1. Get quotes from 2 approved vendors.\n2. Place the purchase order once approved.\n3. Confirm delivery date with the lab in-charge.", priority: "medium", status: "pending", category: "supplies", assigneeId: null, createdAt: "2026-07-14", dueDate: "2026-07-25", estimatedHours: 4, needsHelp: false, timeline: [tl("2026-07-14", "Task created")] },
  { id: "OT-005", title: "Set up chairs for annual day event", description: "Arrange 400 chairs in the main auditorium for the annual day rehearsal and event.", staffInstructions: "1. Coordinate with the event committee on the seating plan.\n2. Set up chairs in rows with center + side aisles.\n3. Leave the front 2 rows reserved.", priority: "high", status: "pending", category: "events", assigneeId: null, createdAt: "2026-07-13", dueDate: "2026-07-18", estimatedHours: 5, needsHelp: false, timeline: [tl("2026-07-13", "Task created")] },
  { id: "OT-006", title: "Repair broken window latch - Library", description: "A window latch on the library's second floor is broken and won't close fully.", staffInstructions: "1. Inspect the latch mechanism.\n2. Replace the latch hardware.\n3. Confirm the window locks securely.", priority: "medium", status: "pending", category: "maintenance", assigneeId: "TM001", createdAt: "2026-07-14", dueDate: "2026-07-16", estimatedHours: 1, needsHelp: false, timeline: [tl("2026-07-14", "Task created and assigned to John Smith")] },
  { id: "OT-007", title: "Prepare monthly security report", description: "Compile the incident log and gate-entry summary for last month.", staffInstructions: "1. Pull the incident log from the security register.\n2. Summarize gate-entry counts by day.\n3. Submit the report to administration.", priority: "low", status: "completed", category: "administrative", assigneeId: "TM003", createdAt: "2026-07-05", dueDate: "2026-07-10", completedAt: "2026-07-09", approvalStatus: "approved", estimatedHours: 2, needsHelp: false, timeline: [tl("2026-07-05", "Task created and assigned to Mike Davis"), tl("2026-07-09", "Marked as done, awaiting approval"), tl("2026-07-10", "Approved by supervisor")] },
  { id: "OT-008", title: "Deep clean cafeteria kitchen", description: "Full deep-clean of the cafeteria kitchen including exhaust hoods and floor drains.", staffInstructions: "1. Clear all surfaces and equipment.\n2. Deep-clean exhaust hoods and floor drains.\n3. Sanitize all food-prep surfaces.", priority: "high", status: "cannot_complete", category: "facilities", assigneeId: "TM004", createdAt: "2026-07-08", dueDate: "2026-07-12", cannotCompleteReason: "Required industrial cleaning equipment is currently under maintenance.", estimatedHours: 3, needsHelp: false, timeline: [tl("2026-07-08", "Task created and assigned to Lisa Chen"), tl("2026-07-12", "Marked as cannot complete")] },
  { id: "OT-009", title: "Replenish first-aid kits across campus", description: "Top up first-aid kits in every building to the standard checklist.", staffInstructions: "1. Audit each building's kit against the standard checklist.\n2. Note missing items per building.\n3. Restock from the medical store.", priority: "medium", status: "in_progress", category: "supplies", assigneeId: "TM005", createdAt: "2026-07-11", dueDate: "2026-07-17", estimatedHours: 2, needsHelp: true, helpNeededReason: "Need approval for additional budget — the medical store's replacement stock is empty.", timeline: [tl("2026-07-11", "Task created and assigned to Tom Wilson"), tl("2026-07-15", "Requested help: budget needed for restocking")] },
  { id: "OT-010", title: "Coordinate parking for alumni event", description: "Arrange overflow parking and signage for the alumni meet this weekend.", staffInstructions: "1. Mark overflow parking area with cones.\n2. Put up directional signage at both gates.\n3. Brief the gate guards on the parking plan.", priority: "medium", status: "pending", category: "events", assigneeId: "TM003", createdAt: "2026-07-14", dueDate: "2026-07-22", estimatedHours: 3, needsHelp: false, timeline: [tl("2026-07-14", "Task created and assigned to Mike Davis")] },
  { id: "OT-011", title: "Inspect fire extinguishers - all blocks", description: "Annual inspection and tagging of fire extinguishers in every academic block.", staffInstructions: "1. Check pressure gauge on every extinguisher.\n2. Tag each with the inspection date.\n3. Flag any needing refill or replacement.", priority: "high", status: "pending", category: "maintenance", assigneeId: "TM001", createdAt: "2026-07-14", dueDate: "2026-07-19", estimatedHours: 4, needsHelp: false, timeline: [tl("2026-07-14", "Task created and assigned to John Smith")] },
  { id: "OT-012", title: "Digitize old admission records", description: "Scan and organize admission records from 2015-2018 into the digital archive.", staffInstructions: "1. Sort paper records by year.\n2. Scan each folder into the archive system.\n3. Verify scanned files against the paper originals.", priority: "low", status: "pending", category: "administrative", assigneeId: null, createdAt: "2026-07-10", dueDate: "2026-08-01", estimatedHours: 6, needsHelp: false, timeline: [tl("2026-07-10", "Task created")] },
  { id: "OT-013", title: "Replace exhaust fan in server room", description: "The server room's exhaust fan is making noise and needs replacement.", staffInstructions: "1. Power down the affected rack section.\n2. Remove and replace the exhaust fan unit.\n3. Confirm airflow and temperature are back to normal.", priority: "high", status: "completed", category: "facilities", assigneeId: "TM001", createdAt: "2026-07-06", dueDate: "2026-07-11", completedAt: "2026-07-11", approvalStatus: "rejected", estimatedHours: 2, notes: "Replacement fan was the wrong model — needs to be redone with the correct part.", needsHelp: false, timeline: [tl("2026-07-06", "Task created and assigned to John Smith"), tl("2026-07-11", "Marked as done, awaiting approval"), tl("2026-07-11", "Rejected by supervisor: wrong replacement part")] },
  { id: "OT-014", title: "Organize sports day equipment", description: "Sort and inventory sports equipment ahead of the annual sports day.", staffInstructions: "1. Pull all equipment from the sports store.\n2. Check condition and discard damaged items.\n3. Organize by event and label crates.", priority: "low", status: "pending", category: "events", assigneeId: "TM005", createdAt: "2026-07-14", dueDate: "2026-07-30", estimatedHours: 3, needsHelp: false, timeline: [tl("2026-07-14", "Task created and assigned to Tom Wilson")] },
  { id: "OT-015", title: "Set up projector for auditorium event", description: "Install and test the projector and screen for this week's guest lecture.", staffInstructions: "1. Mount the projector and connect to the AV rack.\n2. Test the HDMI signal from the podium laptop.\n3. Confirm audio sync with the sound system.", priority: "medium", status: "in_progress", category: "events", assigneeId: "TM001", createdAt: "2026-07-13", dueDate: "2026-07-17", estimatedHours: 2, needsHelp: true, helpNeededReason: "Projector cable is damaged — need a replacement HDMI cable from IT stock.", timeline: [tl("2026-07-13", "Task created and assigned to John Smith"), tl("2026-07-14", "Started working on task"), tl("2026-07-15", "Requested help: needs replacement HDMI cable")] },
];

export function nextTaskId(): string {
  const max = tasks.reduce((m, t) => Math.max(m, Number(t.id.split("-")[1])), 1000);
  return `OT-${String(max + 1).padStart(3, "0")}`;
}
